[package]
name = "botMessenger"
version = "0.1.0"
authors = ["CyberWolf37 <borel.loic.37@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.6"
rocket_codegen = "0.4.6"
log = "0.4.11"
env_logger = "0.8.1"
serde_json = "1.0.59"
http = "0.2.1"
